### ISSUE TITLE
how to submit our implements and validate the results?

### ISSUE THREAD

**Issue by powermano** [Strivin0311/llms-learning#1]

**Comment by Strivin0311** [comment]
Hi, thank you for your attention!

For now, you can just use the `test_toy.py` script by simply running the command `pytest test_toy.py`. This script contains some hard-coded toy cases to get you started.

Soon, we’ll release a more versatile testing script called `test_with_ref.py`. With this script, you’ll be able to create your own test cases and compare the results with **reference implementations** provided as a third-party library.

To offer the reference library in a closed-source manner, we’ll also release a **docker image with the reference code** compiled into its system path.
